name: Penny Stock Bot

on:
  schedule:
    - cron: '30,0 13-20 * * 1-5'  # Run Monday-Friday, 16:30-23:00 IDT (13:30-20:00 UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: python bot.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: bot-results-${{ github.run_id }}  # Unique name with run_id for v4
          path: |
            top_stocks.csv
            bot.log
            penny_stocks.db